import React from 'react';
import * as LucideIcons from 'lucide-react';

export const IconMap = {
  Plus: LucideIcons.Plus,
  Tooth: LucideIcons.Stethoscope,
  Shield: LucideIcons.Shield,
  Sparkles: LucideIcons.Sparkles,
  Sun: LucideIcons.Sun,
  Moon: LucideIcons.Moon,
  Heart: LucideIcons.Heart,
  AlertCircle: LucideIcons.AlertCircle,
  Brush: LucideIcons.Brush,
  Layout: LucideIcons.Layout,
  Scissors: LucideIcons.Scissors,
  Stethoscope: LucideIcons.Stethoscope,
  Scan: LucideIcons.Scan,
  Box: LucideIcons.Box,
  MessageCircle: LucideIcons.MessageCircle,
  Calendar: LucideIcons.Calendar,
  Phone: LucideIcons.Phone,
  Mail: LucideIcons.Mail,
  MapPin: LucideIcons.MapPin,
  Star: LucideIcons.Star,
  CheckCircle2: LucideIcons.CheckCircle2,
  Award: LucideIcons.Award,
  Users: LucideIcons.Users,
  Clock: LucideIcons.Clock,
  Youtube: LucideIcons.Youtube,
  Instagram: LucideIcons.Instagram,
  Navigation: LucideIcons.Navigation,
  Download: LucideIcons.Download,
  Menu: LucideIcons.Menu,
  X: LucideIcons.X,
  ChevronRight: LucideIcons.ChevronRight,
  ChevronLeft: LucideIcons.ChevronLeft,
  ChevronDown: LucideIcons.ChevronDown
};
